### ISSUE TITLE
Can't install anaconda with brew: No available formula

### ISSUE THREAD

**Issue by mzettersten** [lupyanlab/lab-computer#2]
When attempting to install anaconda with homebrew on mac (macOS Sierra Version 10.12.5), I run into the issue that the anaconda formula is not found:

Error: No available formula with the name "anaconda"

I've upgraded homebrew, but still no dice. Are there any steps that need to be taken in installing homebrew to make anaconda available?

**Comment by mzettersten** [comment]
I was able to move forward using cask:

`brew cask install anaconda`

By default, this seems to place anaconda3 in a different location on a mac (/usr/local/ rather than the home directory).

Are there any possible negative consequences from this? Everything went through smoothly so far EXCEPT audio libraries (pygame and pyo).

**Comment by pedmiston** [comment]
Thanks Martin! Ok, I've updated the wiki page with the new brew install instructions and the updated default path location here:

<https://github.com/lupyanlab/lab-computer/wiki/macOS-with-Anaconda-python#1-install-anaconda>.

The difference between `brew install` and `brew cask install` is important. Use `brew install` to install specific packages and libraries, and `brew cask install` to install whole applications. So many things that you install with a .dmg file where you open it and then drag it to your Applications folder can be installed from the command line with `brew cask install`, e.g., `brew cask install google-chrome`.

As for the change in the default Anaconda location, they must have recently changed it from being a per-user install by default to now being a system-wide install by default. Presumably there are reasons for doing this, but regardless it's important to know the newest version.
