### ISSUE TITLE
Error when importing pygame: libSDL-1.2.0.dylib library not found

### ISSUE THREAD

**Issue by mzettersten** [lupyanlab/lab-computer#3]
I installed pygame using the following command

`conda install -c cogsci pygame`

The installation ran through without errors. However, on starting python and attempting to import pygame, I get the following error:

```
>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/__init__.py", line 133, in <module>
    from pygame.base import *
ImportError: dlopen(/usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/base.so, 2): Library not loaded: /usr/local/lib/libSDL-1.2.0.dylib
  Referenced from: /usr/local/anaconda3/envs/psychopy/lib/python2.7/site-packages/pygame/base.so
  Reason: image not found`
```

**Comment by pedmiston** [comment]
Try installing the missing `sdl` dylib with homebrew. You will also likely need the `sdl_mixer` dylib as well. See [here](https://github.com/lupyanlab/lab-computer/issues/9) for more.

`brew install sdl sdl_mixer`

**Comment by mzettersten** [comment]
Before trying your solution, I just tried 

pip install pygame

That seems to have worked. So, not super clean, but maybe one solution.
